### ISSUE TITLE
Hello from a similar project

### ISSUE THREAD

**Issue by nobodxbodon** [kazurof/NiUnit#1]
Hi! It's so glad to find this project. [We](https://github.com/program-in-chinese) are a group of Chinese-speaking developers who are interested in programming in Chinese (name identifiers in Chinese, create APIs in Chinese, Chinese programming langauges, etc), and we just created [Chinese version of JUnit4](https://github.com/program-in-chinese/junit4_in_chinese).

May I ask if you know of other projects that provide APIs or have identifiers in Japanese or other non-English languages?

**Comment by kazurof** [comment]
Hi. sorry I don't know other project.  By the way, I guess you should check https://julialang.org/  if you want to write code in some language other than English.  refer   https://twitter.com/search?q=julia%20unicode

**Comment by nobodxbodon** [comment]
Glad to hear you back. BTW if you mean using unicode variable name, actually lots of programming languages support that: http://rosettacode.org/wiki/Unicode_variable_names

**Comment by kazurof** [comment]
Thank you for your information. but as for actual using example as project, sorry I don't know again.
